// This file has been automatically generated by jagp.

#pragma once

#include <stdint.h>
#include <iostream>
#include <vector>
#include <memory>

#include "Component.h"

/// @brief Packets are created by assembling Components in a particular order.
/// Each Component may be individually defined,
/// or may be itself a Packet to allow for encapsulation of different layer payloads of a stack.
class Packet
{
public:
    Packet() = default;
    virtual ~Packet() = default; // Require a virtual destructor for base class.

    virtual void write(uint8_t *buf, size_t buflen) = 0;
    virtual void read(const uint8_t *buf, size_t buflen) = 0;
};
